# Generated by Django 6.0.3 on 2026-03-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_email_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_complete",
            field=models.BooleanField(default=False),
        ),
    ]
