# Generated by Django 6.0.3 on 2026-03-15 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="rooms.room",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="preferred_room_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("double", "Double"),
                    ("triple", "Triple"),
                ],
                max_length=10,
            ),
        ),
    ]
