# Generated by Django 6.0.3 on 2026-03-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0002_booking_room_alter_booking_preferred_room_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allocation",
            name="qr_status",
            field=models.CharField(
                choices=[
                    ("pending_movein", "Pending Move-in"),
                    ("active", "Active"),
                    ("deactivated_payment", "Deactivated - Payment"),
                    ("deactivated_admin", "Deactivated - Admin"),
                    ("deactivated_vacated", "Deactivated - Vacated"),
                ],
                default="active",
                max_length=30,
            ),
        ),
    ]
