# Generated by Django 6.0.3 on 2026-03-16 09:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReminderSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("remind_hour", models.PositiveSmallIntegerField(default=9)),
                ("remind_minute", models.PositiveSmallIntegerField(default=0)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Reminder Schedule",
            },
        ),
    ]
